export { HeaderSection } from './HeaderSection'
export { BasedSection } from './BasedSection'
export { AboutMeSection } from './AboutMeSection'
export { WorkExperienceSection } from './WorkExperience'
export { SkillsOrbit } from './SkillsOrbit'
