name: Git

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build
        uses: npm install && run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          branch: gh-pages
          folder: build
